{% set name = "relay" %}
{% set version = "18.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebook/relay/archive/v{{ version }}.tar.gz
  sha256: a03f8fdeae217c7fdb12c3f6768a1e023dc930f7c8df53d0f5cbe4dfe2ecdbf5

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - relay --help

about:
  home: https://github.com/facebook/relay
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Relay is a JavaScript framework for building data-driven React applications.
  dev_url: https://github.com/facebook/relay

extra:
  recipe-maintainers:
    - danielnachun
