context:
  version: "19.0.0"

package:
  name: relay
  version: ${{ version }}

source:
  url: https://github.com/facebook/relay/archive/v${{ version }}.tar.gz
  sha256: 8a693abdb05e57e3fa4e61012a6992de865fbeab35e15fd05514e2390b315a8c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    # - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - relay --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Relay is a JavaScript framework for building data-driven React applications.
  homepage: https://github.com/facebook/relay
  repository: https://github.com/facebook/relay

extra:
  recipe-maintainers:
    - danielnachun
