context:
  version: "20.1.0"

package:
  name: relay
  version: ${{ version }}

source:
  url: https://github.com/facebook/relay/archive/v${{ version }}.tar.gz
  sha256: b9eeaaa6cefd396a0e1a57eb568fbb4182d15ecbf43549777eaedb0f800c232a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - relay --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Relay is a JavaScript framework for building data-driven React applications.
  homepage: https://github.com/facebook/relay
  repository: https://github.com/facebook/relay

extra:
  recipe-maintainers:
    - danielnachun
